name: fit_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  curved_labeled_navigation_bar: ^2.0.2
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.7
  fl_chart: ^0.68.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
